from distutils.log import ERROR, error
import json
from re import T
from urllib import response
from elasticsearch import Elasticsearch, helpers
import urllib.request
import datetime
from dateutil.relativedelta import relativedelta
d = datetime.datetime.now()
d = d - relativedelta(days=7)
t = d.strftime('%H')
# Password for the 'elastic' user generated by Elasticsearch
ELASTIC_PASSWORD = "zC4so1Hmvt6PkSqA2UeFH6Aj"

# Found in the 'Manage Deployment' page
CLOUD_ID = "ontology:YXAtbm9ydGhlYXN0LTIuYXdzLmVsYXN0aWMtY2xvdWQuY29tOjQ0MyRmZmE2YzBmM2FlZDU0YjhjODhlMWZhMTEzNjllZDc0OSQ1NjU2NzA4NWYxZDM0NzdkOWY3ZTFmNDk2OTkwODE1NA==kibana"

# Create the client instance

n=10

client = Elasticsearch(
  cloud_id=CLOUD_ID,
  basic_auth=("elastic", ELASTIC_PASSWORD)
)

def collector():
  resultList = [{"target":"apple", "taste":"bad"}, {"target":"banana", "taste": "bad"}]
  resultDict=[]
  id=1
  for data in resultList:
    result = {"_index": "es-index", '_type':"_doc","_id":id,"_source": data, }
    id=id+1
    resultDict.append(result)
    print(resultDict)
    print("hi")
    if len(resultDict) > n:
      print(resultDict)
      helpers.bulk(client, resultDict)
      resultDict = []
      
  helpers.bulk(client, resultDict)

collector()