import json
from elasticsearch import Elasticsearch
import requests
import datetime
from dateutil.relativedelta import relativedelta
d = datetime.datetime.now()
d = d - relativedelta(days=7)


#1시간 마다 UPDATE
# Password for the 'elastic' user generated by Elasticsearch
ELASTIC_PASSWORD = "zC4so1Hmvt6PkSqA2UeFH6Aj"

# Found in the 'Manage Deployment' page
CLOUD_ID = "ontology:YXAtbm9ydGhlYXN0LTIuYXdzLmVsYXN0aWMtY2xvdWQuY29tOjQ0MyRmZmE2YzBmM2FlZDU0YjhjODhlMWZhMTEzNjllZDc0OSQ1NjU2NzA4NWYxZDM0NzdkOWY3ZTFmNDk2OTkwODE1NA==kibana"

# Create the client instance
client = Elasticsearch(
    cloud_id=CLOUD_ID,
    basic_auth=("elastic", ELASTIC_PASSWORD)
)
# Successful response!
# print(client.info())/
ERROR=True
count=1
count_id=0
# 버스 승하차 일일 데이터 노선별 upload 코드
while ERROR:
  url = 'http://openapi.seoul.go.kr:8088/6a4550546c6a683339326965757675/json/SPOP_LOCAL_RESD_JACHI/'+str(count)+'/'+str(count+999)+'/'+d.strftime('%Y%m%d')+'/'+d.strftime('%H')+'/'
#  url = "http://openapi.seoul.go.kr:8088/6a4550546c6a683339326965757675/json/SPOP_LOCAL_RESD_JACHI/1/1/"
  response = requests.get(url)
  json_str = response.content
  json_object = json.loads(json_str)

# bus routenumber, pasgr_num", ali

# "시군구 쿠드,"
  print(json_object)
  print(count)
  for a in range(1000):
    try:
      if json_object["SPOP_LOCAL_RESD_JACHI"]["RESULT"]["CODE"] == 'INFO-000':
        MALE_0 = float(json_object["SPOP_LOCAL_RESD_JACHI"]["row"][a]["MALE_F0T9_LVPOP_CO"])
        MALE_10 = float(json_object["SPOP_LOCAL_RESD_JACHI"]["row"][a]["MALE_F10T14_LVPOP_CO"])+ float(json_object["SPOP_LOCAL_RESD_JACHI"]["row"][a]["MALE_F15T19_LVPOP_CO"])
        MALE_20 = float(json_object["SPOP_LOCAL_RESD_JACHI"]["row"][a]["MALE_F20T24_LVPOP_CO"])+ float(json_object["SPOP_LOCAL_RESD_JACHI"]["row"][a]["MALE_F25T29_LVPOP_CO"])
        MALE_30 = float(json_object["SPOP_LOCAL_RESD_JACHI"]["row"][a]["MALE_F30T34_LVPOP_CO"])+ float(json_object["SPOP_LOCAL_RESD_JACHI"]["row"][a]["MALE_F35T39_LVPOP_CO"])
        MALE_40 = float(json_object["SPOP_LOCAL_RESD_JACHI"]["row"][a]["MALE_F40T44_LVPOP_CO"])+ float(json_object["SPOP_LOCAL_RESD_JACHI"]["row"][a]["MALE_F45T49_LVPOP_CO"])
        MALE_50 = float(json_object["SPOP_LOCAL_RESD_JACHI"]["row"][a]["MALE_F50T54_LVPOP_CO"])+ float(json_object["SPOP_LOCAL_RESD_JACHI"]["row"][a]["MALE_F55T59_LVPOP_CO"])
        MALE_60 = float(json_object["SPOP_LOCAL_RESD_JACHI"]["row"][a]["MALE_F60T64_LVPOP_CO"])+ float(json_object["SPOP_LOCAL_RESD_JACHI"]["row"][a]["MALE_F65T69_LVPOP_CO"])
        MALE_70_UP =float(json_object["SPOP_LOCAL_RESD_JACHI"]["row"][a]["MALE_F70T74_LVPOP_CO"])
        FEMALE_0 = float(json_object["SPOP_LOCAL_RESD_JACHI"]["row"][a]["FEMALE_F0T9_LVPOP_CO"])
        FEMALE_10 = float(json_object["SPOP_LOCAL_RESD_JACHI"]["row"][a]["FEMALE_F10T14_LVPOP_CO"])+ float(json_object["SPOP_LOCAL_RESD_JACHI"]["row"][a]["FEMALE_F15T19_LVPOP_CO"])
        FEMALE_20 = float(json_object["SPOP_LOCAL_RESD_JACHI"]["row"][a]["FEMALE_F20T24_LVPOP_CO"])+ float(json_object["SPOP_LOCAL_RESD_JACHI"]["row"][a]["FEMALE_F25T29_LVPOP_CO"])
        FEMALE_30 = float(json_object["SPOP_LOCAL_RESD_JACHI"]["row"][a]["FEMALE_F30T34_LVPOP_CO"])+ float(json_object["SPOP_LOCAL_RESD_JACHI"]["row"][a]["FEMALE_F35T39_LVPOP_CO"])
        FEMALE_40 = float(json_object["SPOP_LOCAL_RESD_JACHI"]["row"][a]["FEMALE_F40T44_LVPOP_CO"])+ float(json_object["SPOP_LOCAL_RESD_JACHI"]["row"][a]["FEMALE_F45T49_LVPOP_CO"])
        FEMALE_50 = float(json_object["SPOP_LOCAL_RESD_JACHI"]["row"][a]["FEMALE_F50T54_LVPOP_CO"])+ float(json_object["SPOP_LOCAL_RESD_JACHI"]["row"][a]["FEMALE_F55T59_LVPOP_CO"])
        FEMALE_60 = float(json_object["SPOP_LOCAL_RESD_JACHI"]["row"][a]["FEMALE_F60T64_LVPOP_CO"])+ float(json_object["SPOP_LOCAL_RESD_JACHI"]["row"][a]["FEMALE_F65T69_LVPOP_CO"])
        FEMALE_70_UP =float(json_object["SPOP_LOCAL_RESD_JACHI"]["row"][a]["FEMALE_F70T74_LVPOP_CO"])
        TOTAL_MALE=MALE_0+MALE_10+MALE_20+MALE_30+MALE_40+MALE_50+MALE_60+MALE_70_UP
        TOTAL_FEMALE=FEMALE_0+FEMALE_10+FEMALE_20+FEMALE_30+FEMALE_40+FEMALE_50+FEMALE_60+FEMALE_70_UP
        TOTAL_0=MALE_0+FEMALE_0
        TOTAL_10=MALE_10+FEMALE_10
        TOTAL_20=MALE_20+FEMALE_20
        TOTAL_30=MALE_30+FEMALE_30
        TOTAL_40=MALE_40+FEMALE_40
        TOTAL_50=MALE_50+FEMALE_50
        TOTAL_60=MALE_60+FEMALE_60
        TOTAL_70_UP=MALE_70_UP+FEMALE_70_UP
        M_RATE_0 = MALE_0/TOTAL_MALE
        M_RATE_10 = MALE_10/TOTAL_MALE
        M_RATE_20 = MALE_20/TOTAL_MALE
        M_RATE_30 = MALE_30/TOTAL_MALE
        M_RATE_40 = MALE_40/TOTAL_MALE
        M_RATE_50 = MALE_50/TOTAL_MALE
        M_RATE_60 = MALE_60/TOTAL_MALE
        M_RATE_70 = MALE_70_UP/TOTAL_MALE
        F_RATE_0 = FEMALE_0/TOTAL_0
        F_RATE_10 = FEMALE_10/TOTAL_FEMALE
        F_RATE_20 = FEMALE_20/TOTAL_FEMALE
        F_RATE_30 = FEMALE_30/TOTAL_FEMALE
        F_RATE_40 = FEMALE_40/TOTAL_FEMALE
        F_RATE_50 = FEMALE_50/TOTAL_FEMALE
        F_RATE_60 = FEMALE_60/TOTAL_FEMALE
        F_RATE_70 = FEMALE_70_UP/TOTAL_FEMALE
        TOTAL = TOTAL_MALE+TOTAL_FEMALE
        RATE_0 = (MALE_0+FEMALE_0)/TOTAL
        RATE_10 = (MALE_10+FEMALE_10)/TOTAL
        RATE_20 = (MALE_20+FEMALE_20)/TOTAL
        RATE_30 = (MALE_30+FEMALE_30)/TOTAL
        RATE_40 = (MALE_40+FEMALE_40)/TOTAL
        RATE_50 = (MALE_50+FEMALE_50)/TOTAL
        RATE_60 = (MALE_60+FEMALE_60)/TOTAL
        RATE_70 = (MALE_70_UP+FEMALE_70_UP)/TOTAL

        body={
          "sigungu" : json_object["SPOP_LOCAL_RESD_JACHI"]["row"][a]["ADSTRD_CODE_SE"],
          "MALE_0" : MALE_0,
          "MALE_10" : MALE_10,
          "MALE_20" : MALE_20,
          "MALE_30" : MALE_30,
          "MALE_40" : MALE_40,
          "MALE_50" : MALE_50,
          "MALE_60" : MALE_60,
          "MALE_70_UP" : MALE_70_UP,
          "FEMALE_0" : FEMALE_0,
          "FEMALE_10" : FEMALE_10,
          "FEMALE_20" : FEMALE_20,
          "FEMALE_30" : FEMALE_30,
          "FEMALE_40" : FEMALE_40,
          "FEMALE_50" : FEMALE_50,
          "FEMALE_60" : FEMALE_60,
          "FEMALE_70_UP" : FEMALE_70_UP,
          "TOTAL_MALE" : TOTAL_MALE,
          "TOTAL_FEMALE" : TOTAL_FEMALE,
          "TOTAL_0" : TOTAL_0,
          "TOTAL_10" : TOTAL_10,
          "TOTAL_20" : TOTAL_20,
          "TOTAL_30" : TOTAL_30,
          "TOTAL_40" : TOTAL_40,
          "TOTAL_50" : TOTAL_50,
          "TOTAL_60" : TOTAL_60,
          "TOTAL_70_UP" : TOTAL_70_UP,
          "M_RATE_0" : M_RATE_0,
          "M_RATE_10" : M_RATE_10,
          "M_RATE_20" : M_RATE_20,        
          "M_RATE_30" : M_RATE_30,
          "M_RATE_40" : M_RATE_40,
          "M_RATE_50" : M_RATE_50,
          "M_RATE_60" : M_RATE_60,
          "M_RATE_70" : M_RATE_70,  
          "F_RATE_0" : F_RATE_0,
          "F_RATE_10" : F_RATE_10,
          "F_RATE_20" : F_RATE_20,        
          "F_RATE_30" : F_RATE_30,
          "F_RATE_40" : F_RATE_40,
          "F_RATE_50" : F_RATE_50,
          "F_RATE_60" : F_RATE_60,
          "F_RATE_70" : F_RATE_70,  
          "RATE_0" : RATE_0,
          "RATE_10" : RATE_10,
          "RATE_20" : RATE_20,
          "RATE_30" : RATE_30,
          "RATE_40" : RATE_40,
          "RATE_50" : RATE_50,
          "RATE_60" : RATE_60,
          "RATE_70" : RATE_70,
        }

        client.index(index="seoullifepopluation1", id=count, body=body)
        count=count+1
        ERROR=True
      else:
        ERROR=False
    except:
      ERROR=False
print(count)

result=client.reindex(
  source= {"index":"노선별정류장별승하차정보와행정동코드조인1"},
  dest = {
    "index" : "노선별정류장별승하차정보와행정동코드조인100",
    "pipeline": "노선별정류장별승하차정보와행정동코드조인100-pipeline"
  },
)
print(result)

result=client.reindex(
  source= {"index":"노선별정류장별승하차정보와행정동코드조인100"},
  dest = {
    "index" : "생활인구와노선별정류장별승하차정보와행정동코드조인100과조인4",
    "pipeline": "생활인구와노선별정류장별승하차정보와행정동코드조인100과조인4-pipe"
  },
  wait_for_completion=False
)

print(result)

  #       body={
  #         "BUS_ROUTE_NO" : json_object["CardBusStatisticsServiceNew"]["row"][a]["BUS_ROUTE_NO"],
  #         'ARS-ID' : json_object["CardBusStatisticsServiceNew"]["row"][a]["BSST_ARS_NO"],
  # 
  #         '시군구코드' : 
  #         'RIDE_PASGR_NUM' : json_object["CardBusStatisticsServiceNew"]["row"][a]["RIDE_PASGR_NUM"],
  #         'ALIGHT_PASGR_NUM' : json_object["CardBusStatisticsServiceNew"]["row"][a]["ALIGHT_PASGR_NUM"]
  #       }